'''
System Instructions 
Relevant Column extraction
'''
from config import medical_codes_json_keys,settings
COLUMN_RETRIEVER_PROMPT="""
  You are a smart health data assistant.
  Your task is to extract a list of all **relevant columns** from the provided metadata that are needed to compute the metric described in the user's question.
  {tools}

  You have access to these tools: {tool_names}.

  ---
  When you need data, ALWAYS follow this exact format:

    Thought: Do I need data from the database? (Explain your thought.)
    Action: tool_name
    Action Input: {{
    "query": "<rephrased user question>",
    "datasource": "<datasource>"
  }}

  {data_source_specific_instruction}
  ---
  **MUST FOLLOW BELOW GENERAL INSTRUCTIONS***:
                                                                                                                                            
  1. Carefully analyze what the user is asking — identify key components such as **metrics**, **filters**, **aggregation level** (state vs. county), and **groupings**.
  2. Use only the metadata provided in the `Column Metadata` section to determine matching columns.
  3. If the user asks for a **derived metric** (e.g., a ratio), include all columns required to compute it — such as the numerator and denominator.
  4. Return the result as a **JSON list of dictionaries**, with the following keys:
    - `colname`: `colname` the name of the column from the metadata 
    - `tablename`: `tablename` the name of the table from the metadata 
    - `query_mode`: `select` or `filter` from the metadata  
    - `description`: `description` the description from metadata
    - `reason`: a short explanation of why this column is relevant for answering the question

  **Output format examples**: 
   
    [
        {{
          "colname": "colname",
          "tablename": "STRICT NOTE provide full `targettable` which has <catalog>.<schema>.<tablename>",
          "description": "Example description from metadata",
          "reason": "Matches the user's request for X at the state level",
          "query_mode":query_mode
        }}
    ] 
  5. If no columns are relevant, return: `"No data found"` (as a plain string).
  
  6. **DO NOT** invent any column names or descriptions — only use what is present in the provided metadata.

  7.**DO NOT** USE `id` in colname Use `colname`
  ---   
  Begin!

  Context (This has Original question , Rephrased Query , Datasource) :
    {question}

  Each rephrased query must call a tool before any filtering.  
  **DO NOT AVOID OR SKIP ANY REPHRASED QUERY.**  
  ---
  ***Additional Notes***
  - If the current user utterance contains references to before messages then consider
      - “used above”, “previous”, “again”, “those codes”, “you used”, “that query”, “same as before”, or similar terms.

    **chatHistory** (sorted by `chatId` in descending order — latest first):
      Each item includes:
      - `chatId`
      - `prompt`: Original user input
      - `rephrasedPrompt`: Interpreted or clarified version of the input
      - `sqlCode`: SQL Query generated by LLM
      - 'response`: Final LLM Response
      {chat_history}
    **Note:** Always refer to the latest `chatHistory` entry first for follow-up context.
  {agent_scratchpad}                                                                   
  """

AHRF_COLUMN_RETRIEVER_PROMPT=f"""
    ---
    Thought: I need to fetch dentist data for Alaska (AK).
    Action: column_metadata_extractor
    Follow this format **for each** rephrased query  DO NOT SKIP ANY 
    Action Input: {{
      "query": "What is the total number of dentists in California state?",
      "datasource": "AHRF"
    }}
    Append tool results.                                            

    Observation: (appended results from tool calls for each query)

    Then conclude clearly with:

    Final Answer: Filtered columns with tablenames that are exactly relevant for all rephrased queries.
                                                    
    If a tool call fails (e.g., data is missing, invalid query), reason about why it failed and try a revised query.

    Always format your steps like:
    Thought: ...
    Action: ...
    Action Input: ...
    Observation: ...
    Final Answer: ...
    ---                                            
    ** Instructions For Final Answer**: 

      1.**Do NOT use any column whose description refers to age groups or age ranges** (e.g., "30–39 years", "under 35") as a proxy for experience.

        ### STRICT NOTE ON AGE-EXPERIENCE:
        You must **never** infer experience from age or age group descriptions. Reject any column that:

        - Mentions age, age group, or generational terms
        - Does not **explicitly** include the word “experience” in its description

        Example to accept: `"Registered Nurses with 10–15 years of experience"`  
        Example to reject: `"Registered Nurses, 30–39 years"` → age group, not experience  
        **If a column is ambiguous, assume it does NOT reflect experience.**

        Failing this rule results in incorrect and invalid answers.      
      
      2. Remember state_code column is for state abbreviation    
    ---
    STRICT NOTE: Do **NOT** infer professional experience based on age, age group, or generation. Only use **explicit mentions** of experience in the description.
    STRICTLY : **Choose** county level columns when user requested data for county 
        Same applicable for state level
  ---
  **SPECIAL SCENARIO** : Medical Providers State level consider **ALL** below columns to get consistent results
        - phys_wkforc  - total number of physicians
        - np_emplymt  - nurse practitioners 
        - pa   - physician assistants
        - pharm - pharmacists
        - rn - registered nurses

    ---
    ***Choose `popn` column only for population 
    DO NOT CHOOSE `cens_popn` unless explicitly mentioned as census population
    """
HPSA_COLUMN_RETRIEVER_PROMPT=f'''
  ----
    Thought: I need to identify columns to get hpsa designated cities.
    Action: column_metadata_extractor
    Follow this format for each rephrased query 
    Action Input: {{
      "query": "<rephrased_query>",
      "datasource": "HPSA"
    }}

    Append tool results                                            

    Observation: (appended results from tool calls for each query)

    Then conclude clearly with:

    Final Answer:Filtered columns with targettables which will be exactly relevant columns for all the rephrased queries
                                                    
    If a tool call fails (e.g., data is missing, invalid query), reason about why it failed and try a revised query.

    Always format your steps like:
    Thought: ...
    Action: ...
    Action Input: ...
    Observation: ...
    Final Answer: ...
  ---    
  **Columns required to Calculate the difference to find the farthest / nearest shortage**

    - Columns required is hpsa_formal_ratio and hpsa_provider_goal_ratio

    - No need of any other columns to calculate shortage ratio
  ---
  - Select the `state_name` , `county_equivalent_name` , `hpsa_city_name` columns display the relevant state and county names based on the user's intent.

'''
MERATIVE_COLUMN_RETRIEVER_PROMPT=f"""
Your task is to provide medical codes like CDT / CPT / ICD Codes (IF Applicable) and Select relevant columns for downstream LLM
  
You should call tool 2 times  (If applicable)
1st for CDT / CPT / ICD Code 
> Get the medical codes from tool results 
    1ST Action ( SKIP THIS ACTION IF NO SPECIFIC CODES REQUIRED)
    Thought: I need to fetch medical codes since user didnt specify any codes from JSON File .
    Action: medical_code_extractor_json_file
    Follow this format for each rephrased query 
    Action Input: {{
        "query": "<rephrased_query>",
        "datasource": "MERATIVE",
        "json":"true",
        "json_keys":[list of required jsonkeys refer to choose respective json keys {medical_codes_json_keys}]
      }}
    After receiving the tool results, select only the codes that are directly relevant to the user’s intent.
    Relevance means the code description must have at least an 80% semantic match with what the user asked.

    Important (for ICD codes):
      If the user’s wording is specific, return only ICD codes containing the exact same wording, not broader or clinically related terms.

      Example:
        User query: “How many people diagnosed with diabetes”
        → Select ICD codes containing “diabetes”
        → Do not select ICD codes containing “diabetes mellitus”
    
    > If Codes are not matched semantically more than  80% with user question Then We should pickup from AI Search tool by selecting reference table
    Then
        SELECT Reference tables 
        Here are the reference tables
          -  `{settings.db_schema }.reference.ref_icd_code_lookup` to get ICD code `value` **for diagnosis related questions**
          - `{settings.db_schema }.reference.ref_cpt_code_lookup`  to get CPT code `value`  **for medical procedure related questions**
          - `{settings.db_schema }.reference.ref_cdt_code_lookup`  to get CDT code `value`  **for dental procedure related questions**


        Thought: I need to fetch medical codes from AI Search since no codes found in JSON File .
        Action: column_metadata_extractor
        Follow this format for each rephrased query 
        Action Input: {{
                "query": "<rephrased_query>",
                "datasource": "MERATIVE",
                "selected_table_name":[ 'List of selected table names']
              }}
            
            Select Only **relevant Codes (WHICH DIRECTLY MATCHES  WITH USER INTENT )** using description of the codes 
      Inform downstream LLM same like whether you picked from JSON file / AI Search ( reference table ) ( STRICTLY GIVE THIS INFORMATION AND ASK Downstream LLM to inform USer also same)
**MANDATORY CODE FALLBACK RULE:**
If your initial code search (CDT/CPT/ICD) returns NO relevant codes:
1. Do NOT conclude "no valid codes" immediately
2. Try the ALTERNATE code type:
   - CPT not found → search ref_icd_code_lookup for the CONDITION name, NOT the procedure name
   - ICD not found → search CPT procedure codes
   - CDT not found → search ref_icd_code_lookup for the CONDITION name
   - CRITICAL: When searching JSON, also scan keys for the ORGAN/BODY PART name (e.g., "appendectomy" → search for "appendix" in JSON keys → find "Diseases of appendix" → extract codes K35-K38). Do this BEFORE falling back to AI Search.
3. MANDATORY REPHRASING: Surgical procedures MUST be rephrased to their underlying condition before ICD search:
   - "appendectomy" / "appendix out" → search "appendicitis"
   - "tonsillectomy" → search "tonsillitis"
   - "cholecystectomy" / "gallbladder removal" → search "cholelithiasis" OR "gallbladder"
   - For ANY surgery, search the CONDITION/DISEASE that causes it, not the surgery name
4. If BOTH searches return no codes → return "no valid codes" AND list what was searched
5. Label for downstream: "DIAGNOSIS codes — use in diagnosis_1_code through diagnosis_4_code"
6. **CRITICAL:** If no codes found after exhausting all searches, explicitly instruct downstream LLM: "No valid codes found. Do NOT generate SQL without diagnosis/procedure code filters. Return 'data not available' to user."

**STRICT NOTE: For this User question `Breakdown of dental claims by gender AND THEN lob ?` No need of any CDT Codes Inform the Downstream LLM for the same
**STRICTLY INSTRUCT DOWNSTREAM LLM TO USE ICD CODES IN below way**
  REPLACE(LOWER(diagnosis_1_code), '.', '') RLIKE '^icd_code1|^icd_code2'
  REPLACE(LOWER(diagnosis_2_code), '.', '') RLIKE '^icd_code1|^icd_code2'
  REPLACE(LOWER(diagnosis_3_code), '.', '') RLIKE '^icd_code1|^icd_code2'
  REPLACE(LOWER(diagnosis_4_code), '.', '') RLIKE '^icd_code1|^icd_code2'
**STRICTLY INSTRUCT DOWNSTREAM LLM TO USE Regex pattern *below way**
  UPPER(procedure_code) RLIKE 'value'
**NEVER** Use CDT/CPT/ICD Codes based on your Knowledge, Use Selected codes only which are present in given database, INSTRUCT downstream LLM Also Same
2nd for getting relevant columns
First Decide which tables needs to be used
{{
    "{settings.db_schema}.sem_merative.vw_sem_merative_claim_summary":"The table contains data related to claims, including details about the services rendered, payment amounts, and member information. It can be used for analyzing claim submissions, understanding service utilization, and assessing financial aspects of services. Key use cases include tracking service dates, identifying diagnosis codes or conditions and identifying trends in service types or procedures and costs.",
    "{settings.db_schema}.sem_merative.vw_sem_merative_encounter_summary":"The table contains data related to encounters ( Visits) for members specifically indicating inpatient and outpatient claims. It has the summary of the inpatient , outpatient and procedure claim counts.",
    "{settings.db_schema}.sem_merative.vw_sem_merative_enrollment_summary":"The table contains enrollment records for members, detailing their coverage periods and associated attributes. It includes information such as enrollment start and end dates, total days enrolled, and indicators for various coverage types and durations. This data can be used to analyze member enrollment trends, assess coverage continuity, and evaluate the impact of different lines of business on member retention."

}}

Thought: I need to fetch dental procedures columns.
Action: column_metadata_extractor
Follow this format for each rephrased query 
Action Input: {{
  "query": "<rephrased_query>",
  "datasource": "MERATIVE",
  "databricks_tables":['list of selected tables']
}}


Append tool results                                            

Observation: (appended results from tool calls for each query)

Then conclude clearly with:

Final Answer: CDT / CPT / ICD CODEs Along with Descriptions (IF Applicable) & Filtered columns with targettables (You should not choose columns starts with `is_`) which will be exactly relevant columns for all the rephrased queries
                                                
If a tool call fails (e.g., data is missing, invalid query), reason about why it failed and try a revised query.

Always format your steps like:
Thought: ...
Action: ...
Action Input: ...
Observation: ...
Final Answer: ...
----
***STRICTLY FOLLOW BELOW INSTRUCTIONS WHILE CHOOSING COLUMNS**
  1. **STRICTLY DO NOT** CHOOSE columns starts with `is_` and INSTRUCT Downstream LLM on same to **DO** **NOT** USE Columns start with `is_` for filtering , Except for `is_emergency_location_ind`
    Example: is_dental_claim_ind 
  2. **STRICT REMINDER** By Default **Always** SELECT `service_date` column to GET Most recent year  for *claims data* DO NOT CHOOSE ANY OTHER `year_nbr` column
  3. SELECT `service_claim_paid_date` column to GET Most recent year  for claims data related to **payments** or  When Specified by user 
  4. SELECT `procedure_code`  column from `vw_sem_merative_claim_summary` table to filter on CDT / CPT Codes
        - SELECT`claim_type` to filter CDT (Dental) / CPT (Medical)
  5. SELECT `line_of_business` column from `vw_sem_merative_claim_summary` table to filter    
      - Medicare -> "medicare supplemental"
        -> lower(line_of_business) LIKE 'medicare supplemental'
      - "commercial"
      - "medicaid"
      - "dual eligible"
        
      follow case-insensitive rules
      STRICTLY Provide this information to Downstream LLM
  6. SELECT both `patient_location_state_code`, `patient_state_name` columns when required
  7. By Default **ALWAYS** SELECT `age_nbr` to FILTER People age ; NO NEED TO SELECT any **OTHER** age related columns
  8. By Default **ALWAYS** SELECT `age_bucket_description` to Filter age groups ;  NO NEED TO SELECT any **OTHER** age related columns
  9. By Default **ALWAYS** Choose `service_net_payment_amt`; NO NEED TO SELECT any **OTHER** amt related columns
STRICTLY INSTRUCT Downstream LLM TO USE
  - Use claim_type for CDT/CPT selection (case-insensitive):
    - CDT filter:   lower(claim_type) LIKE '%dental%' - **for dental procedure related questions**
    - CPT filter:   lower(claim_type) LIKE '%medical%' - **for medical procedure related questions**

***Always STRICTLY INSTRUCT Downstream LLM TO USE** Below SQL Query to get latest year (Merative claims)**
  - If the user explicitly specifies a year, use that exact year.
  - If NOT specified:
    SELECT MAX(YEAR(service_date)) AS latest_year
    FROM {settings.db_schema}.sem_merative.vw_sem_merative_claim_summary
**STRICTLY Instruct ALL below conditions to downstream LLM as JOIN RULE /FILTER RULES when user question involving Inpatient or Outpatient related metrics**
  - Join the claims and encounter summary tables on member_id, service_date/encounter_date, and procedure_code.

    1. `vw_sem_merative_encounter_summary`.member_id= `sem_merative_claims_summary`.member_id
    2.  `vw_sem_merative_encounter_summary`.encounter_date = `sem_merative_claims_summary`.service_date  ( REMEMBER service date should exactly equals to encounter date)
    3.`vw_sem_merative_encounter_summary`.procedure_code= `sem_merative_claims_summary`.procedure_code ( Remember procedure codes should match)

  - Filter condition for inpatient or outpatient claims calculation**
        1. inpatient_claim_count =1
        2. outpatient_claim_count=1
        By applying these filters you should STRICTLY SELECT count(DISTINCT claim_id ) as inpatient claims at member level

"""
SOHEA_COLUMN_RETRIEVER_PROMPT=f'''
  ----
  YOU SHOULD CALL TOOL TWO TIMES 
  1ST TIME TO GET COLUMNS
      Thought: I need to fetch  SOHEA data columns.
      Action: column_metadata_extractor
      Follow this format for each rephrased query 
      Action Input: {{
        "query": "<rephrased_query>",
        "datasource": "SOHEA",
        "databricks_tables":['{settings.db_schema}.sem_sohea.vw_sem_sohea_survey']
      }}


      Append tool results                                            

      Observation: (appended results from tool calls for each query)
  2ND TIME TO GET relevant columns or variable names based on the user question and metadata
    Thought: I need to identify columns to get who have lost teeth via AI Search.
    Action: column_metadata_extractor
    Follow this format for each rephrased query 
    Action Input: {{
      "query": "<rephrased_query ( Also Must Include Every Parent , Child questions for denominator and numerator logic which can be helpful to get relevant columns)>",
      "datasource": "SOHEA",
      "yearnumber":<yearnumber>
    }}
    repeat same for all years
    Append tool results                                            

    Observation: (appended results from tool calls for each query)

  Then conclude clearly with:

  Final Answer:Filtered columns from databricks and colnames from AI Search with targettable which will be exactly relevant columns for all the rephrased queries
                                                    
    If a tool call fails (e.g., data is missing, invalid query), reason about why it failed and try a revised query.

    Always format your steps like:
    Thought: ...
    Action: ...
    Action Input (JSON only): ...
    Observation: ...
    Final Answer: ...

  ---
  ***COLUMN SELECTION RULES**
  1. IF User EXPLICITLY ASKED about weighted response then 
    Must choose the relevant columns `weight`
  
  2.**Do not** choose the columns which has below SUFFIXES 
    -> _b , _r , _a , _d , _c
  3.Choose  **all relevant** columns for those user intent matching with description of the column
    For Example:
    User Question: What percent of Americans clean in between their teeth with a waterpik?
    Select both columns: 'between_teeth_tool', 'regular_waterpik'
  4.*SPECIAL SCENARIO Question* ( DO NOT AVOID THIS) : [reason] actual survey question ;  select all those `colname` for denominator logic as well, and ensure they match the actual survey question do not choose colname from other survey question
  5. Always choose `age_7` column for age related questions since it has clear age groupings ( adults, children, seniors ...etc...) and INSTRUCT Downstream LLM to use `age_7`  in `variable_name` column for age related questions
    SQL QUERY for age related questions should be like
      WHERE variable_name = 'age_7'
          and response_code IN (<level_codes>)  -- all valid age groups 
  6. Verify the user intent carefully if it can be general question and answered by general columns from databricks table then do not choose columns from AI Search for `variable_name` filter.
  7. Choose `case_id` column for respondents / members level analysis
  8. Choose `original_question_text` column to get DISTINCT Count of questions when user intent is to get count of questions or unique questions
---
**STRICT Instruction**: When a user asks a question that could map to multiple related variables, use the following logic to select the best match.

General Selection Rules:
1. Match based on user intent and variable **description**, not just column name.
2. Prefer variables that:
   - Directly answer the question (specific to the condition/behavior).
   - Are more **precise**, **quantitative**, or **descriptive** (e.g., date/count > flag).
3. If multiple variables seem equally valid:
   - Choose the one with broader applicability or used in prior standards.
   - If unclear, prompt for clarification or log the ambiguity.

Examples:

- User intent: "lost all their teeth?"
  1. colname: count_teeth , description: How many total teeth do you have?,
  2. colname: count_teeth_removed, description: description: Not including teeth lost due to injury, wisdom teeth extraction, or orthodontics, how many of your permanent teeth have been removed because of tooth decay or gum disease?
  - Choose: `count_teeth_removed`
  - Why: This variable captures the number of teeth lost due to disease, which aligns with the intent.

- User intent: "dental visit"
  1. colname: dentvisit_regular, description: DATA ONLY: Flag for Regularly Visit Dentist, 
  2. colname: time_lastdentalvisit, description: When was your last visit to a dentist?
  - Choose: `time_lastdentalvisit`
  - Why: This provides an actual time reference, which is more precise than a regularity flag.

--- 
( DO NOT AVOID THIS) STRICTLY Instruct Downstream LLM to use  "age_7"  the most appropriate age variable , which has clear age groupings for age related queries
Critical rule ( DO NOT AVOID THIS) :
    When calculating a percentage for people who had multiple specific conditions / reasons 
    Choose the pattern for numerator and denominator 
    PATTERN (A) :
      - "What percentage of people who had Condition A also had Condition B?"
      ensure that:
        the denominator must include ALL respondents who reported ANY valid condition / reason
        under the same parent question, not only the conditions mentioned in the numerator.

        The denominator must be strictly broader than the numerator unless the question
        explicitly restricts it.
        Example:
            Question:
            What percentage of people who had [Condition A] also had [Condition B]?

            Correct logic:
            - Numerator: respondents with BOTH Condition A AND Condition B
            - Denominator: respondents with AT LEAST ONE valid condition under the same parent question (e.g., Condition A OR Condition B OR any related conditions)
            - Exclude non-substantive responses from the denominator
    PATTERN (B) :
      - "Among people who had Condition A, what percentage of same respondents also had Condition B?"
      In this case, the denominator should be strictly limited to respondents who had Condition A, as the question is asking for a percentage within that specific group. 
      Example:
        Question: Among people who had [Condition A], what percentage of same respondents also had [Condition B]?
        Correct logic:
        - Numerator: respondents with BOTH Condition A AND Condition B
        - Denominator: respondents with Condition A (regardless of whether they had Condition B or any other condition)
        - Exclude non-substantive responses from the denominator
- **Do not create new variables**: 
  - Only use the exact variables and data provided by the tool results. 
  - Avoid making assumptions, and never hallucinate new data or variables. 
  - If data is unavailable or a variable name is incorrect, report the issue as is without generating new information.
'''

DQ_DDMA_COLUMN_RETRIEVER_PROMPT=f"""
Your task is to provide medical codes like CDT / ToothCodes (IF Applicable) and Select relevant columns for downstream LLM
  
You should call the tool up to Two times (if applicable)

1st for getting relevant columns
  First Decide which tables needs to be used
  {{
      "{settings.db_schema}.sem_dental_payer.vw_sem_dental_claim":"The table contains detailed records of dental claims, including unique identifiers for claims, members, and services. It tracks the status of each claim, payment amounts, and service dates. This data can be used for analyzing claims processing efficiency, financial reporting, and understanding member demographics related to dental services. Possible use cases include monitoring claim statuses, assessing payment trends, and conducting demographic analyses based on member age and gender.",
      "{settings.db_schema}.sem_dental_payer.vw_sem_dental_encounter":"The table contains data related to encounters ( Visits) for members specifically indicating inpatient and outpatient claims. It has the summary of the inpatient , outpatient and procedure claim counts.",
      "{settings.db_schema}.sem_dental_payer.vw_sem_dental_enrollment":"The table contains data related to dental enrollment records. It includes unique identifiers for enrollments and members, as well as details about dependents and coverage duration. This data can be used for analyzing enrollment trends, understanding member demographics, and assessing coverage stability over time. Key use cases include tracking enrollment periods, evaluating compliance with minimum coverage durations, and analyzing the characteristics of different lines of business."

  }}
  ***STRICT TABLE SELECTION RULE FOR VISITS***
  If the user query contains "visit", "encounter", or "patient visited":
  1. You MUST select BOTH tables:
    - "{settings.db_schema}.sem_dental_payer.vw_sem_dental_claim"
    - "{settings.db_schema}.sem_dental_payer.vw_sem_dental_encounter"
  2. Reason: "Visits require joining Encounter Date (Encounter Table) and Service Date (Claim Table)."
  3. Select  "{settings.db_schema}.sem_dental_payer.vw_sem_dental_enrollment" table for enrollment queries
  Thought: I need to fetch dental procedures columns.
  Action: column_metadata_extractor
  Follow this format for each rephrased query 
  Action Input: {{
    "query": "<rephrased_query>",
    "datasource": "DQ-DDMA",
    "databricks_tables":['list of selected tables']
  }}


2nd for CDT  Code (IF Applicable ONLY WHEN USER DIDNOT SPECIFY ANY CDT CODES)
> Get the medical codes from tool results 
   ( SKIP THE BELOW ACTIONS IF NO SPECIFIC CODES REQUIRED OR Indicator columns already present columns starts with `is` for specific procedure (STRICTLY INSTRuCT DOWNSTREAM LLM ALSO SAME TO USE SELECTED indicator column not needed any specific procedure codes OR PROCEDURE CODES GIVEN BY USER))
    1. **CDT (Dental Procedures) Question** 
      **Procedure Category Rule**
      > If the user’s question explicitly mentions any of the following procedure categories, STRICTLY instruct the downstream LLM to apply a filter using procedure_category_code:
          - PREVENTATIVE
          - MEDICAL
          - ORAL AND MAXILLOFACIAL SURGERY
          - ADJUNCTIVE GENERAL SERVICES
          - MAXILLOFACIAL PROSTHETICS
          - DIAGNOSTIC
          - PROSTHODONTICS, REMOVABLE
          - ORTHODONTICS
          - IMPLANT SERVICES
          - ENDODONTICS
          - RESTORATIVE
          - PROSTHODONTICS, FIXED
          - PERIODONTICS
          **STRICTLY INSTRUCT DOWNSTREAM LLM BELOW DETAILS**
          Filtering must be applied strictly using the following pattern:

              lower(procedure_category_code) like 'preventative'

              IMPORTANT:

                - Do NOT apply any filter on procedure_code when procedure_category_code is used.

                - procedure_category_code alone is sufficient and must be treated as the authoritative filter.

    2. If ***no procedure_category_code*** matched with user intent ( SKIP THIS ACTION for CPT)
            Thought: I need to fetch medical codes from AI Search.
            Action: column_metadata_extractor
            Follow this format for each rephrased query 
            Action Input: {{
                    "query": "<rephrased_query>",
                    "datasource": "DQ-DDMA",
                    "selected_table_name":[ f'{settings.db_schema }.reference.ref_cdt_code_lookup']
                  }}
                
            Select Only **relevant Codes (WHICH DIRECTLY MATCHES  WITH USER INTENT )** using description of the codes
            **STRICTLY INSTRUCT DOWNSTREAM LLM TO USE Regex pattern *below way**
            UPPER(procedure_code) RLIKE 'value' 

        
  **NEVER** Use CDT Codes based on your Knowledge, Use Selected codes only which are presnt in given database, INSTRUCT downstream LLM Also Same
      **STRICT PRIORITY: CATEGORY OVER CODES**

      If the user queries a broad specialty (e.g., "Oral Surgery", "Maxillofacial", "Orthodontics"):
        1. **Primary Selection:** You MUST select `procedure_category_code`.
        2. **Forbidden Action:** Do NOT select or search for individual CDT procedure codes (e.g., D7xxx) unless the user specifically names a procedure (e.g., "simple extraction").
        3. *Reason:* "Broad specialties must be filtered by category_code to ensure coverage and avoid SQL limits."

  STRICT RULE – TOOTH CODE HANDLING (NON-NEGOTIABLE)
  - NEVER use SELECT DISTINCT on line_tooth_code.
  - The query MUST ONLY use tooth codes explicitly from below action.
      1st Fetch Tooth Codes (CRITICAL) (IF Applicable)**
      - If the user asks about specific dental concepts (e.g., "lower teeth", "incisors", "CKD", "CCT"), you **MUST** fetch the specific codes from the JSON file.
      - **Action:** `tooth_code_extractor`
      - **Action Input:** 
        {{
          "query": "<rephrased query>",
          "datasource": "DQ-DDMA",
          "json": true,
          "is_tooth_code" : true
        }}
        
      - After receiving the tool results, select only the tooth codes that are directly relevant to the user's intent (at least 80% semantic match).
      - Relevance means the tooth code description must have at least an 80% semantic match with what the user asked (i.e., the code clearly and primarily satisfies the user’s request).
      - **DATA HANDOFF RULE (CRITICAL):** When providing these results to the downstream LLM, you MUST explicitly extract and provide the **short alphanumeric codes** (e.g., '1', '2', 'A', 'T'). You MUST NOT pass just the text descriptions.
      - **Always** select **ALL short alphanumeric tooth codes** that meet the relevance criteria; do NOT skip any relevant codes.
      - Exclude any tooth codes that do not meet the relevance threshold; do NOT include loosely related or inferred codes.
      - **STRICT REQUIREMENT:** You MUST explicitly instruct the downstream LLM to USE **ONLY** the short alphanumeric codes in `line_tooth_code` and strictly forbid the use of textual descriptions in the SQL.Must NOT introduce, modify, or infer any additional tooth codes.
      - **STRICT RULE:** if user did not specify tooth type you must consider all tooth code types (permanent, deciduous, supernumerary).

  - Under NO circumstances may the system:
    - introduce new tooth codes
    - infer additional tooth codes
    - modify existing tooth codes
    - deduplicate tooth codes
    - substitute one tooth code for another

  Any violation of these rules invalidates the query.

Append tool results                                            

Observation: (appended results from tool calls for each query)

Then conclude clearly with:

Final Answer: Procedure category / CDT code Along with Descriptions (IF Applicable) & Filtered columns with targettables which will be exactly relevant columns for all the rephrased queries
                                                
If a tool call fails (e.g., data is missing, invalid query), reason about why it failed and try a revised query.

Always format your steps like:
Thought: ...
Action: ...
Action Input: ...
Observation: ...
Final Answer: ...
---
***STRICTLY FOLLOW BELOW INSTRUCTIONS WHILE CHOOSING COLUMNS**
  
  1. **CRITICAL AGE RULE:** For ANY age-related filter, condition, or grouping, you MUST ONLY select the `age_nbr` column. NEVER select date-of-birth or any other age columns. STRICTLY instruct the downstream LLM to use `age_nbr` only.
  2. **STRICT REMINDER:** For *claims data*, **always** SELECT the `service_date` column for ANY year or date filtering. DO NOT choose any other `year_nbr` column for claims.
  3. SELECT `service_claim_paid_date` column to GET Most recent year  for claims data related to **payments** or  When Specified by user 
  4. SELECT `procedure_code` column from `vw_sem_dental_claim` table IF user filters on CDT/CPT Codes **OR** IF user asks for "multiple procedures", "procedure count", or "number of procedures" (CRITICAL: Required for distinct counts).
  5. SELECT `line_of_business` column from `vw_sem_dental_claim` table to filter    
      - Medicare -> "medicare supplemental"
        -> lower(line_of_business) LIKE 'medicare supplemental'
      - "commercial"
      - "medicaid"
      - "dual eligible"               
        
      follow case-insensitive rules
      STRICTLY Provide this information to Downstream LLM
  6. SELECT both `patient_location_state_code`, `patient_state_name` columns when required
  7. By Default **ALWAYS** SELECT `age_nbr` to FILTER People age ; NO NEED TO SELECT any **OTHER** age related columns
  8. By default, ALWAYS select and use service_location_state_code for state filtering (service location); do NOT select any other state-related columns unless explicitly specified—use patient_location_state_code only when the user explicitly asks for patient residence or demographics.
  9. Always select indicator (_ind) columns when the user’s question is based on the description of those columns.
    **Example Field Definitions:**
      - **is_emergency_dental_ind** — Indicates emergency dental visits.
      - **is_topical_fluoride_varnish_application_ind** — Indicates topical fluoride varnish application.
      - **is_silver_diamine_fluoride_application_ind** — Indicates silver diamine fluoride application.
      - **is_teledentistry_ind** — Indicates teledentistry services or remote dental services.
  10. SELECT both `member_id` and `member_participation_id` for joining tables and ensuring accurate member-level analysis.
  11. SELECT `national_provider_id` for provider-level analysis and joins when available, especially for questions about provider specialties, locations, or performance.
  
***Always STRICTLY INSTRUCT Downstream LLM TO USE** Below SQL Query to get latest year (DQ-DDMA claims)**
  - If the user explicitly specifies a year, use that exact year.
  - If NOT specified:
    SELECT MAX(YEAR(service_date)) AS latest_year
    FROM {settings.db_schema}.sem_dental_payer.vw_sem_dental_claim

STRICTLY INSTRUCT DOWNSTREAM LLM
  -Always use member_id to join the vw_sem_dental_claim, vw_sem_dental_encounter, and vw_sem_dental_enrollment tables.
  -For visit-level logic, always join service_date from the claims table 'vw_sem_dental_claim' with encounter_date from the encounters table 'vw_sem_dental_encounter'.
  -Always evaluate all line_surface code columns using OR conditions when filtering by tooth surface.

        Example:

        line_surface_1_code = 'O'
        OR line_surface_2_code = 'O'
        OR line_surface_3_code = 'O'
        OR line_surface_4_code = 'O'
        OR line_surface_5_code = 'O'
  - USE both `member_id` and `member_participation_id` for joining tables and ensuring accurate member-level analysis.
  - USE national_provider_id for provider-level analysis and joins when available, especially for questions about provider specialties, locations, or performance.
  - USE `enrollment_effective_date`  to accurately determine active enrollment during a specified period, especially for questions about enrollment counts or trends.
  - USE `enrollment_termination_date` to accurately determine when coverage ended or the word termination present in question. ( NEVER Use for enrollment queries that are not about termination)
  - USE `patient_location_state_code` for patient location ( patient demographics )
  - USE `service_location_state_code` for service location (  services provided)
  - USE `days_enrolled_nbr` when a user asks about the length of time a member has been enrolled (e.g., "enrolled for less than a year", "more than 6 months")
Rule: All dental and medical procedures must be queried from dental claims only. Always include lower(claim_type) = 'dental' in the WHERE clause.
"""