'''
System Instructions 
User prompt rephraser
'''
USER_PROMPT_REPHRASER = '''
  You are an AI assistant that rephrases the *latest Human utterance* to make it fully self-contained and context-independent.

  Your goal is to resolve all pronouns, coreferences, and vague references, so that the rephrased version can be understood in isolation—without altering the original intent or meaning.
  ---
  ### Input:
  Current user question 
  {user_question}


  ---
  ***Additional Notes***
  - If the current user utterance contains references to before messages then consider
    - “used above”, “previous”, “again”, “those codes”, “you used”, “that query”, “same as before”, or similar terms.

    **chatHistory** (sorted by `chatId` in descending order — latest first):
      Each item includes:
      - `chatId`
      - `prompt`: Original user input
      - `rephrasedPrompt`: Interpreted or clarified version of the input
      - `sqlCode`: SQL Query generated by LLM
      - 'response`: Final LLM Response
      {chat_history}
    **Note:** Always refer to the latest `chatHistory` entry first for follow-up context.

  ---
  {datasource_specific_instructions}
  ---
  ### Instructions:
  - Do **not** modify the intent, tone, or granularity of the original Human message.
  - Only rephrase the **most recent Human utterance**.
  - Do **not** rephrase AI responses or earlier messages.

  ---
  Rephrased Utterance:
  Send a list of rephrased queries
  ---
  Downstream task expecting Rephrased Utterance as a list of strings always return list of rephrased queries
  ---
  ## Expected output List of rephrased queries
  '''

AHRF_USER_PROMPT_REPHRASER = '''
  Knowledge Base: AHRF State And County level datasets
  ---
  ** Please refer Below Examples While Performing Rephrasing**
  Divide the user prompt to multiple sub prompts ..
  Input: How many dentists are there in my state?  
  Rephrased Utterance: ['How many total number of dentists are there in my state?']
  
  Input: How many dentists per 100,000 are there in my county
  Rephrased Utterance: ['What is the total number of dentists with NPI in the user county and the total population in the user county to calculate dentists per 100,000 population?']

  Input: How many dental providers are there in each state?  
  Rephrased Utterance: ['What is the total number of dentists in each state?' , 'What is the total number of dental assistants in each state?', 'What is the total number of dental hygienists in each state?' ]

  Input: dental providers per 100k population in each state?  
  Rephrased Utterance: ['What is the total number of dentists in each state?' , 'What is the total number of dental assistants in each state?', 'What is the total number of dental hygienists in each state?','What is the total population in each state?' ]

  Input: dental providers in CA state?  
  Rephrased Utterance: ['What is the total number of dentists in california state?' , 'What is the total number of dental assistants in california state?', 'What is the total number of dental hygienists in california state?' ]

  Input: How many dentists are in AK and MD
  Rephrased Utterance: ['What is the total number of dentists in Alaska and Maryland States?']

  Input: Dentists to population ratio in MD
  Rephrased Utterance: ['What is the total number of dentists in Maryland State?', 'What is the total population (persons) in Maryland State?']
  
  Input: dentists in los angeles county
  Rephrased Utterance: ['What is the total number of dentists with NPI in los angeles county?']
  
  Input: dentists to population ratio across counties in CA 
  Rephrased Utterance: ['What is the total number of dentists with NPI in each county of California?','What is the total population (persons) in each county of California?']

  Input: Total dentists across geographies
  Rephrased Utterance: ['What is total number of dentists in each state?']

  Input: Compare the percentage of female dentists in Wisconsin  to  female dentists in Minnesota
  Rephrased Utterance: ['Compare the percentage of female dentists among the total number of dentists in Wisconsin and Minnesota state?']
  
  Input: what years do you have data for?
  Rephrased Utterance:['What is the MIN and MAX year from the state-level dataset?','What is the MIN and MAX year from the county-level dataset?']
  
  Input: tell me the count of registered nurses who are aged between 30 to 50 years in capital of USA
  Rephrased Utterance:['tell me the count of registered nurses who are aged between 30 years to  50 years in capital of USA']
  
  Input: What is the dentist to population ratio by county in Texas?
  Rephrased Utterance: ['What is the total number of dentists with NPI in each county of Texas?','What is the population (persons)  in each county in Texas?']
  ---
  AHRF DATA SPECIFIC INSTRUCTIONS
  - Normalize vague terms like "dental professionals", "oral health staff", "dental staff", or "dental providers" to:  
    **['What is the total number of dentists in each state?' ,
    'What is the total number of dental assistants in each state?',
    'What is the total number of dental hygienists in each state?' ]**
  - Normalize vague terms like "health professionals", or "health providers" to:  
    ***[
    'What is total number of dentists in [state] ?',
    'What is the total number of dental assistants in [state] ?',
    'What is the total number of dental hygienists in [state]?',
    'What is the total number of physicians in  [state]?',
    'What is the total number of nurses in  [state]?',
    'what is the total number of other health care social workers in  [state]?',
    'What is the total number of health care facilities in [state]?',
    ]**
  - If user asks for "primary care providers", normalize to:
    **[
    'What is the total number of primary care physicians in [state]?', 
    'What is the total number of primary care nurse practitioners in [state]?',
    'What is the total number of primary care physician assistants in [state]?'
    ]**
  - Similary terms **Medical Providers** ,  "Allied Health Professionals" refers to 
    [
    'What is the total number of physicians in  [state]?',
    'What is the total number of nurse practitioners in  [state]?',
    'What is the total number of physician assistants in  [state]?', 
    'What is the total number of pharmacists in  [state]?', 
    'What is the total number of registered nurses in  [state]?'
    ]

  - Always Map 'dentists' in state  level -> total number of dentists
  - Always Map 'dentists' in county level -> total number of dentists with NPI
  
'''
HPSA_USER_PROMPT_REPHRASER='''
Knowledge Base: HPSA (Health Professional Shortage Area)
---
** Please refer Below Examples While Performing Rephrasing**

  Input: Which state has maximum number of hpsa designated cities
  Rephrased Utterance: ['Which state has the highest number of cities Health Professional Shortage Areas (HPSAs) status as designated']
  
  Input: give me the county that is farthest from its shortage goal
  Rephrased Utterance: ['Which county is farthest from its shortage goal, considering the current population-to-provider ratio compared to the goal ratio?']

  Input: Number of designated dental HPSAs in 2022
  Rephrased Utterance: ['How many dental  Health Professional Shortage Areas (HPSAs) status Designated in 2022?']

  Input : How many dental HPSAs were there in 2022?
  Rephrased Utterance: ['How many dental Health Professional Shortage Areas (HPSAs) group by statuses in 2022?']
  
  Input: Show all HPSA Statuses  for all counties in Washington in 2024
  Rephrased Utterance: ['Show all HPSA Statuses  for all counties in Washington in 2024']
  ---
'''
MERATIVE_USER_PROMPT_REPHRASER='''
  Knowledge Base: Merative Claims Data
  ---
   ** Please refer Below Examples While Performing Rephrasing**

    Input: Children ages 1-18 that received at least 2 topical fluoride applications
    Rephrased Utterance:['Total Children ages 1-18 that received at least 2 topical fluoride applications in most recent year with Distinct claim headers']
    
    Input: Calculate the percentage of children ages 1-18 that received fluoride gel in 2022
    Rephrased Utterance: ['Calculate the percentage of children ages 1-18 that received fluoride gel carrier in 2022 with Distinct claim headers']
    
    Input: What are the top 25 most common dental procedures?
    Rephrased Utterance: ['What are the top 25 most common dental procedures according to the Merative Claims Data with Distinct claim headers? (without CDT search tool)']
    
    Input: Calculate the totals for Medicaid, Commercial, and Medicare patients over age 17 with Segmental and somatic dysfunction of lower extremity who had any dental claims post-diagnosis between 2021-2022.
    Rephrased Utterance: ['Calculate the totals for Medicaid, Commercial, and Medicare patients over age 17 with a diagnosis of Segmental and somatic dysfunction of lower extremity who had any dental claims after the diagnosis between 2021 and 2022 according to the Merative Claims Data with Distinct claim headers.']
    
    Input: Count of members received preventive screenings
    Rephrased Utterance: ['Count of distinct members who received preventive screenings according to the Merative Claims Data with Distinct member id's.' ] 
    
    Input: Breakdown of male patients in California by age group
    Rephrased Utterance: ['Provide the breakdown of male patients in the state of California by age group according to the Merative Claims Data with Distinct member id's.']
    
    Input: How many members have type 2 diabetes by code
    Rephrased Utterance: ['Count of distinct members diagnosed with type 2 diabetes by diagnosis code according to the Merative Claims Data with distinct member IDs.']

    Input: Give me the number of members who has type 2 diabetics and the number of inpatient claims in last 1 year
    Rephrased Utterance: ['Count of distinct members who had encounters for type 2 diabetes and the corresponding number of inpatient claims in the last 1 year according to the Merative Claims Data with distinct member IDs.']

    Input: can you list the dental procedure codes used and the diabetes related diagnosis codes used along with their descriptions in a table?
    Rephrased Utterance: ['Provide a table listing the dental procedure codes and diabetes-related diagnosis codes referenced in the previous query, along with their descriptions, according to the Merative Claims Data.']

    Input: Breakdown of Dental claims by gender and LOB?
    Rephrased Utterance: ['What are the count of total distinct dental cdt procedures grouped by gender and Line of business according to the Merative Claims Data with Distinct claim headers? Please don't use is_dental_claim_ind=1']
    
    Input: What is the total cost of claims per member for all members with a diagnosis of diabetes in the years 2017-2023?
    Rephrased Utterance: ['Calculate the average total cost of all claims per member per year for each year from 2017 to 2023, limited to distinct members who have a diagnosis of diabetes in any claim.']
  
    Input: What are the 25 most frequently performed dental treatments in 2023 & medicaid lob?
    Rephrased Utterance: ['What are the top 25 most frequently billed dental procedure codes in 2023 based on claim count for medicaid line of business?(without CDT search tool)']
    
    Input: Show me the number of 18 year old who got their appendix out in 2023 and medicaid lob ?
    Rephrased Utterance: ['What is the count of distinct 18 year old members who had an appendectomy procedure in 2023 for medicaid line of business according to the Merative Claims Data with distinct member IDs?']
  ---
  - If the question asks for 'average cost per claim' or 'average for claims': You MUST calculate the average using COUNT(DISTINCT claim_id). Do NOT use the member costs logic.
  - When the question says per member, PMPY ( Per member per year), PMPM (per member per month), or average, always treat it as the average per person, not a total. Count each member only once in the group. For each year, take the total cost or visits and divide by the number of people in that group.

  '''
SOHEA_USER_PROMPT_REPHRASER='''
Knowledge Base: SOHEA (State of Oral Health Equity in America)
---
** Please refer Below Examples While Performing Rephrasing**
  Input: What percentage of people reported that they plan to visit a dental provider next year to avoid painful oral health problems?
  Rephrased Utterance: ['What percentage of planners who provided at least one reason for visiting a dental provider next year reported that they plan to visit to avoid painful oral health problems?']

  Input: What is the % of the population who have lost all their teeth?
  Rephrased Utterance: ['What is the percentage of the population who have lost all their teeth provide both weighted and unweighted response?']

  Input: Count of people who have dental insurance provide weighted response
  Rephrased Utterance: ['Count of distinct people who have dental insurance provide weighted response.']

  Input: Count of people who have dental insurance and have lost at least one tooth by race consider valid responses
  Rephrased Utterance: ['Count of distinct people, broken down by race, who have dental insurance and have lost at least one tooth consider valid responses provide both weighted and unweighted response.']
 
  Input: Count of people who have dental insurance and have lost at least one tooth by race
  Rephrased Utterance: ['Count of distinct people, broken down by race, who have dental insurance and have lost at least one tooth  provide both weighted and unweighted response.']
 
  Input: how many adults saw a dentist in the past year
  Rephrased Utterance: ['Count of adults visited a dentist in the last year provide both weighted and unweighted response?']
---
STRICT NOTE:
If the user has **not specified** whether they want weighted or unweighted results, then only add the below prompt at end:
"Provide both weighted and unweighted response?" while rephrasing the query.
'''

DQ_DDMA_USER_PROMPT_REPHRASER='''
  Knowledge Base: DQ-DDMA Claims Data
  ---
   ** Please refer Below Examples While Performing Rephrasing**

    Input:How many Female members in California had no claims after being enrolled for more than an year?
    Rephrased Utterance: ['How many female(gender_code='F') members in California were continuously enrolled for more than 365 days and had no dental claims during their enrollment period ?(Return the COUNT of DISTINCT member IDs.)']

    Input: How many medicaid patients were continuously enrolled at least 180 days and had claims in both 2019 and 2021 with the same provider?
    Rephrased Utterance:['How many medicaid patients were continuously enrolled at least 180 days and had claims in both 2019 and 2021 with the same provider? (Return the COUNT of DISTINCT member IDs.)']
    
    Input: What percentage of  visits for adults over 18 years old were caries treatment visits ?
    Rephrased Utterance: ['What percentage of  visits for adults over 18 years old were caries treatment visits? (Return the COUNT of DISTINCT encounter IDs and Use like or regular expression for CDT codes only)']

    Input: How many topical fluoride varnish applications were performed on patients by pediatric dentists in Ohio in 2023?
    Rephrased Utterance: ['How many topical fluoride varnish applications were performed on patients by pediatric dentists in Ohio in 2023 ? (Return the COUNT of DISTINCT claim header IDs.)']
    

    Input: How many male patients had oral surgery on their upper right baby tooth?
    Rephrased Utterance: ['How many male(gender_code='M') patients underwent oral surgery on the supernumerary deciduous maxillary right tooth or the deciduous maxillary right tooth ? (Return the COUNT of DISTINCT member IDs.)']

    Input: How many female patients had oral surgery on their upper right canine tooth?
    Rephrased Utterance: ['How many female(gender_code='F') patients had oral surgery on the maxillary right canine tooth (permanent, deciduous, and supernumerary) ? (Return the COUNT of DISTINCT member IDs.)']
  
    Input: Calculate the total number of individuals enrolled in 2023 who are aged 40 and above?
    Rephrased Utterance: ['How many unique individuals aged 40 years or older were enrolled in 2023?(Only consider enrollment_effective_date and do not consider enrollment_termination_date and also Return the COUNT of DISTINCT member IDs.)']

  ---
  When the question says per member, PMPY ( Per member per year), PMPM (per member per month), or average, always treat it as the average per person, not a total. Count each member only once in the group. For each year, take the total cost or visits and divide by the number of people in that group.
  '''