'''
Test cases - accuracy check
'''
# This file defines a TestAgent class that uses a ReAct agent to validate the SQL queries generated by the AI Data Explorer against expected SQL queries for given questions.
# It compares the structure, logic, and results of the expected SQL with the application-generated SQL and produces a detailed JSON report on the accuracy of the generated SQL.
# The functionality_test function is used to run the test multiple times to gather results from different sessions for comparison.

# Import necessary modules for agent creation, LLM connection, configuration, and utility functions
from datetime import datetime

from langchain.agents import create_react_agent, AgentExecutor
from langchain_openai import AzureChatOpenAI
from config import settings
from services.agent_tools_ import functionality_test_tool
from langchain.prompts import PromptTemplate
import services as services
import uuid

# Prompt template for the testing agent, instructing it how to validate SQL and results
testing_agent_prompt_template = """

You are a **SQL Query and Final Result Validator** agent.

Your job:
1. Use the provided tools to fetch  expected SQL results.
2. Compare their structure, logic, and data with provided results generated from different sessions.
3. Produce a detailed JSON report including accuracy.

---

### Available TOOLS:
1. fetch_record(sql_query: str)
   → Executes SQL and returns expected result.


{tools}

Tool Names: {tool_names}
Datasource: {datasource}

---

### Test Case
{test_case}

---

### HOW TO THINK AND ACT
You must follow this reasoning loop **exactly** every time:

#### Step 1 — Fetch Expected Result
Thought: I should use the `fetch_record` tool to get results for the expected SQL query.
Action: fetch_record
Action Input: f"<expected SQL query >"
Observation: <expected result>
append the expected result to the final JSON report for comparison in the next step.

#### Step 2 — Compare and Conclude , Produce JSON Report NO Further actions needed after this step
Thought: Now I will compare the expected SQL, generated SQL, and their respective results to determine correctness and accuracy.
Prodcude a JSON report with the following format for each session's generated SQL and results
Final Answer:

[
  {{
    "session": 1,
    "question": "<input prompt>",
    "expected_sql": "<expected SQL>",
    "generated_sql": "<generated SQL>",
    "sql_match": true,
    "expected_result": "<expected SQL result>",
    "generated_result": "<application result in a readable format>",
    "result_match": true,
    "status": "PASS",
    "failure_reason": "Detailed reason with specific mismatches if any"
  }},
  {{
    "session": 2,
    "question": "<input prompt>",
    "expected_sql": "<expected SQL>",
    "generated_sql": "<generated SQL>",
    "sql_match": false,
    "expected_result": "<expected SQL result>",
    "generated_result": "<application result in a readable format>",
    "result_match": false,
    "status": "FAIL",
    "failure_reason": "Detailed reason with specific mismatches if any"
  }}
]
***NOTE**: 
- `status` is PASS if results match, regardless of SQL match.
- If results do not match, `status` is FAIL with detailed failure reason.
- `failure_reason` should specify if the failure is due to result mismatch and provide details on what exactly did not match (e.g., missing filter, incorrect aggregation, wrong columns, etc.)
- If results match but SQL does not, note the SQL mismatch in `failure_reason` but set `status` to PASS.
---
RULES

Every “Thought:” must be followed by an “Action:” and “Action Input:” exactly in this order.

Only use the tools listed above.

Never skip the “Observation:” step.

Stop after producing the final JSON block in “Final Answer”.

Do not include any additional explanations after the JSON output
---
Begin!

User Input: {input}
---
{agent_scratchpad}
"""


# Function to test the AI Data Explorer chatbot functionality by running the same question multiple times
def functionality_test(question, datasource, no_of_iters=1):
  """
  Runs the chatbot for a given question and datasource multiple times to collect responses from different sessions.
  Args:
    question (str): The input question to test.
    datasource (str): The datasource to use.
    no_of_iters (int): Number of test iterations/sessions.
  Returns:
    list: List of responses from each session.
  """
  results = []
  run_time_per_session = []
  for i in range(no_of_iters):  # Run the test `no_of_iters` times to get results from different sessions
    session_time_start = datetime.now()
    print(f"\n--- Running test iteration {i+1} ---")
    # Generate a unique session ID for each test run
    response_stream = services.chatbot(uuid.uuid4().hex, question, datasource, 'ai_test_user@test.com')
    session_end_time = datetime.now()
    
    coolected_response = ""
    # Collect the streamed response
    for chunk in response_stream:
      print(chunk, end="", flush=True)
      coolected_response += chunk
    results.append(coolected_response)
    run_time_per_session.append(str(session_end_time - session_time_start))
  return results,run_time_per_session
# Create a PromptTemplate object from the testing agent prompt template
testing_agent_prompt_template_ = PromptTemplate.from_template(testing_agent_prompt_template+
f''' ***STRICT RULES FOR EXPECTED SQL QUERY IN TEST CASES:(Before calling `fetch_record` tool)***
- ALWAYS use {settings.db_schema} as the catalog name in the expected SQL query.
- ALWAYS use the exact schema and table names as shown in the application-generated SQL (<catalogname>.<schemaname>.<tablename> format).
- NEVER modify, abbreviate, substitute, or alias schema or table names. Any deviation is strictly forbidden.
- DO NOT use alternate names, aliases, or omit catalog/schema/table references unless explicitly required by application logic.
- DO NOT add, remove, or reorder catalog, schema, or table references.
''') 

# TestAgent class encapsulates logic for running test cases using a ReAct agent
class TestAgent:
  def __init__(self, datasource):
    """
    Initializes the TestAgent with the appropriate LLM configuration for the given datasource.
    Args:
      datasource (str): The datasource to use for testing.
    """
    self.datasource = datasource
    # Find the LLM config key that matches the datasource, or use 'default' if not found
    self.llm_config_key = next(
      (key for key in settings.LLM_Config.keys() if datasource.lower() in key.lower()),
      'default'  # default if no match found
    )
    # Initialize the AzureChatOpenAI connector with the selected config
    self.llm_connector_agent = AzureChatOpenAI(
      azure_deployment=settings.LLM_Config[self.llm_config_key]['deployment_name'],
      api_version=settings.LLM_Config[self.llm_config_key]['api_version'],
      azure_endpoint=settings.LLM_Config[self.llm_config_key]['endpoint'],
      api_key=settings.LLM_Config[self.llm_config_key]['subscription_key'],
      temperature=0,
      max_tokens=None,
      timeout=30,
      max_retries=1,
      model_kwargs={"stream_options": {"include_usage": True}}
    )

  def run_test_case(self, question, expected_sql, results_from_sessions):
    """
    Runs a test case by prompting the agent to compare expected and generated SQL/results.
    Args:
      question (str): The input question for the test case.
      expected_sql (str): The expected SQL query.
      results_from_sessions (list): List of generated SQL/results from different sessions.
    Returns:
      dict: The agent's response containing the comparison and accuracy report.
    """
    # Prepare the prompt for the agent with the test case details
    testing_agent_prompt = testing_agent_prompt_template_.partial(
      datasource=self.datasource,
      test_case=f'''Question: {question}
        Expected SQL: {expected_sql},
        Application-generated SQL and Results from  different sessions: {results_from_sessions}
        '''
    )

    # Create the ReAct agent for testing
    testing_agent = create_react_agent(
      self.llm_connector_agent,
      functionality_test_tool,
      testing_agent_prompt
    )
    # Set up the agent executor to run the test
    test_executor_agent = AgentExecutor(
      agent=testing_agent,
      tools=functionality_test_tool,
      verbose=True,
      handle_parsing_errors=True,  # handles output formatting errors
      max_iterations=5,
      return_intermediate_steps=True
    )
    # Invoke the agent with the test input
    response = test_executor_agent.invoke({
      "input": "Compare expected vs generated SQL and results for this test case."
    })
    return response